import PDFDocument from 'pdfkit';
import { ComplianceFiling, ComplianceFilingType, ComplianceFilingPeriod } from '../compliance.model';
import { complianceAssetService } from './asset.service';
import mongoose from 'mongoose';

/**
 * Service for generating compliance filing reports (PDF).
 */
class ComplianceReportService {
  /**
   * Generate PDF report for a filing
   */
  async generateReportForFiling(filingId: string, createdBy: mongoose.Types.ObjectId): Promise<string> {
    const filing = await ComplianceFiling.findById(filingId)
      .populate('filingTypeId')
      .populate('periodId')
      .populate('createdBy', 'name email');

    if (!filing) {
      throw new Error('Filing not found');
    }

    const filingType = filing.filingTypeId as any;
    const period = filing.periodId as any;

    // Generate PDF
    const doc = new PDFDocument({ margin: 50 });
    const chunks: Buffer[] = [];

    doc.on('data', (chunk) => chunks.push(chunk));

    // Header
    doc.fontSize(20).text('Compliance Filing Report', { align: 'center' });
    doc.moveDown();

    // Filing Details
    doc.fontSize(14).text('Filing Details', { underline: true });
    doc.moveDown(0.5);
    doc.fontSize(12);
    doc.text(`Type: ${filingType.name} (${filingType.code})`);
    doc.text(`Period: ${period.label}`);
    doc.text(`Amount: ${filingType.currency} ${filing.amount.toLocaleString()}`);
    doc.text(`Statutory Due Date: ${filing.statutoryDueDate.toLocaleDateString()}`);
    if (filing.internalDueDate) {
      doc.text(`Internal Due Date: ${filing.internalDueDate.toLocaleDateString()}`);
    }
    doc.text(`Status: ${filing.status}`);
    if (filing.filedAt) {
      doc.text(`Filed Date: ${filing.filedAt.toLocaleDateString()}`);
    }
    if (filing.paymentReference) {
      doc.text(`Payment Reference: ${filing.paymentReference}`);
    }
    doc.moveDown();

    // Company Info (if available from config)
    doc.fontSize(14).text('Company Information', { underline: true });
    doc.moveDown(0.5);
    doc.fontSize(12);
    doc.text('Generated by ZyberHR Compliance Module');
    doc.text(`Generated on: ${new Date().toLocaleDateString()}`);
    if (filing.createdBy) {
      const creator = filing.createdBy as any;
      doc.text(`Created by: ${creator.name || creator.email}`);
    }
    doc.moveDown();

    // Notes
    if (filing.notes) {
      doc.fontSize(14).text('Notes', { underline: true });
      doc.moveDown(0.5);
      doc.fontSize(12).text(filing.notes);
    }

    // Wait for PDF to be generated
    const pdfBuffer = await new Promise<Buffer>((resolve, reject) => {
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);
      doc.end();
    });

    // Upload to S3 and create asset
    const asset = await complianceAssetService.uploadAsset({
      buffer: pdfBuffer,
      fileName: `filing-report-${filingType.code}-${period.year}-${period.month}.pdf`,
      mimeType: 'application/pdf',
      prefix: 'filings',
      entityId: filingId,
      createdBy,
      applyImmutability: false, // Reports don't need Object Lock, receipts do
    });

    // Add asset to filing
    filing.reportAssets.push(asset._id);
    await filing.save();

    return asset._id.toString();
  }
}

export const complianceReportService = new ComplianceReportService();
